# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

name=${project.name}
version=${project.version}
artifactId=${project.artifactId}
authlibApiUrl=https://amereco.ru/wp-json/authlib-api/v1/yggdrasil/